### ISSUE TITLE
Internal Server Error (500) - Server Error saat membuka menu Sinkronisasi Dapodik

### ISSUE THREAD

**Issue by alidihaw** [eraporsmk/erapor7#10]
**Deskripsi yang jelas dan ringkas, sertakan screenshot/gif jika diperlukan**
Aplikasi yang sedang dipakai:
1. Operating System: -
2. Versi Aplikasi: 7.0.1
3. Versi Database: 6.0.0
4. Hosting: https://rapor.smkbaiturrahman.sch.id

Internal Server Error (500) - Server Error saat membuka menu Sinkronisasi Dapodik

<img width="1440" alt="Screenshot 2023-09-29 at 13 19 19" src="https://github.com/eraporsmk/erapor7/assets/135804399/02c45bae-59a2-448c-bd86-46c3a152654c">

<img width="1440" alt="Screenshot 2023-09-29 at 13 42 35" src="https://github.com/eraporsmk/erapor7/assets/58108579/64c7f7ab-d807-4489-95bc-8b6af100e5ba">

**Comment by eraporsmk** [comment]
Silahkan kirim file laravel.log yang ada di folder root_erapor/storage/logs ke eraporsmk@gmail.com

Terima Kasih

**Comment by alidihaw** [comment]
```
[2023-09-29 14:02:25] local.ERROR: Class "finfo" not found {"userId":"f97dbb49-4402-4104-985d-a65d2fc4e205","exception":"[object] (Error(code: 0): Class \"finfo\" not found at /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/league/mime-type-detection/src/FinfoMimeTypeDetector.php:48)
[stacktrace]
#0 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/league/flysystem-local/LocalFilesystemAdapter.php(84): League\\MimeTypeDetection\\FinfoMimeTypeDetector->__construct()
#1 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(184): League\\Flysystem\\Local\\LocalFilesystemAdapter->__construct()
#2 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(152): Illuminate\\Filesystem\\FilesystemManager->createLocalDriver()
#3 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(120): Illuminate\\Filesystem\\FilesystemManager->resolve()
#4 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(83): Illuminate\\Filesystem\\FilesystemManager->get()
#5 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\\Filesystem\\FilesystemManager->disk()
#6 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/app/Http/Controllers/SinkronisasiController.php(31): Illuminate\\Support\\Facades\\Facade::__callStatic()
#7 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\SinkronisasiController->index()
#8 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#9 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#10 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#11 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#12 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#13 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#15 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(126): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(102): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#17 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(54): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter()
#18 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#19 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#21 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#23 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#25 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#27 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#28 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#30 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#32 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#34 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(34): Illuminate\\Pipeline\\Pipeline->then()
#36 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->handle()
#37 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Pipeline\\Pipeline->then()
#39 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#40 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#41 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#42 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#43 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#44 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#46 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#47 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#49 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#50 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#52 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#54 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#56 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#58 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#59 /home/smkbaitu/rapor.smkbaiturrahman.sch.id/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#60 {main}
"} 

```
disini aja ya kak, cuman sedikit

**Comment by alidihaw** [comment]
sudah bisa ya, karena kurang php extension
