### ISSUE TITLE
EROR SAAT DI HOSTING

### ISSUE THREAD

**Issue by wayan1998** [eraporsmk/erapor7#99]
[11-Jun-2024 00:34:41 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined method Error::getStatusCode() in /home/smknmop2/erapor.smkn1mopuya.sch.id/app/Exceptions/Handler.php:55
Stack trace:
#0 /home/smknmop2/erapor.smkn1mopuya.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(439): App\Exceptions\Handler->App\Exceptions\{closure}()
#1 /home/smknmop2/erapor.smkn1mopuya.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(369): Illuminate\Foundation\Exceptions\Handler->renderViaCallbacks()
#2 /home/smknmop2/erapor.smkn1mopuya.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): Illuminate\Foundation\Exceptions\Handler->render()
#3 /home/smknmop2/erapor.smkn1mopuya.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse()
#4 /home/smknmop2/erapor.smkn1mopuya.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#5 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#6 {main}
  thrown in /home/smknmop2/erapor.smkn1mopuya.sch.id/app/Exceptions/Handler.php on line 55
![Screenshot 2024-06-11 020518](https://github.com/eraporsmk/erapor7/assets/172308247/7dfb9963-1b6f-4761-b145-6807742a3101)
![Screenshot 2024-06-11 012548](https://github.com/eraporsmk/erapor7/assets/172308247/7d387242-2a58-4d0e-8194-58b98e29d84c)

**Comment by wayan1998** [comment]
MOHON BANTUANYA

**Comment by masadi** [comment]
Coba git pull pak

Pada Sel, 11 Jun 2024, 01.06, wayan1998 ***@***.***> menulis:

**Comment by wayan1998** [comment]
gmna caranya pak

**Comment by wayan1998** [comment]
udah di git pull 
tapi belum bisa pak
![Screenshot 2024-06-11 075726](https://github.com/eraporsmk/erapor7/assets/172308247/6254ba5d-5e0d-4125-a1f0-888c62b08411)

**Comment by itnsapurbalingga** [comment]
> [11-Jun-2024 00:34:41 Asia/Jakarta] PHP Fatal error: Uncaught Error: Call to undefined method Error::getStatusCode() in /home/smknmop2/erapor.smkn1mopuya.sch.id/app/Exceptions/Handler.php:55 Stack trace: #0 /home/smknmop2/erapor.smkn1mopuya.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(439): App\Exceptions\Handler->App\Exceptions{closure}() #1 /home/smknmop2/erapor.smkn1mopuya.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(369): Illuminate\Foundation\Exceptions\Handler->renderViaCallbacks() #2 /home/smknmop2/erapor.smkn1mopuya.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): Illuminate\Foundation\Exceptions\Handler->render() #3 /home/smknmop2/erapor.smkn1mopuya.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse() #4 /home/smknmop2/erapor.smkn1mopuya.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException() #5 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap{closure}() #6 {main} thrown in /home/smknmop2/erapor.smkn1mopuya.sch.id/app/Exceptions/Handler.php on line 55 ![Screenshot 2024-06-11 020518](https://private-user-images.githubusercontent.com/172308247/338295353-7dfb9963-1b6f-4761-b145-6807742a3101.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTIwMzksIm5iZiI6MTcxODA5MTczOSwicGF0aCI6Ii8xNzIzMDgyNDcvMzM4Mjk1MzUzLTdkZmI5OTYzLTFiNmYtNDc2MS1iMTQ1LTY4MDc3NDJhMzEwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwNzQyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTVlYWVlYzkyMGUwNGUzYmE1NWI2MzBmNmI1MDIxN2ZjNGU5ZjFiZjQ1OWZlM2Q0ODFjZjZlYjc4M2RlODEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B4drdC-gtT4V3V-yFlhduRO2sfSvE0riZf7yDsLYarw) ![Screenshot 2024-06-11 012548](https://private-user-images.githubusercontent.com/172308247/338295393-7d387242-2a58-4d0e-8194-58b98e29d84c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTIwMzksIm5iZiI6MTcxODA5MTczOSwicGF0aCI6Ii8xNzIzMDgyNDcvMzM4Mjk1MzkzLTdkMzg3MjQyLTJhNTgtNGQwZS04MTk0LTU4Yjk4ZTI5ZDg0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwNzQyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTcwNTg4YzY3ZjI3M2VlYjk2ZGYyM2UzZTJhOTBiMDhkMzI2OTJjNmZkNGFkMjYxM2ExZmIxMmE3ZDVmOTgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xtBbAEzuh2MaYiIYYwBSEbRmHzdpHjwozt_F9hsHBiE)

Apakah hostingnya support database postgresql

**Comment by wayan1998** [comment]
> > [11-Jun-2024 00:34:41 Asia/Jakarta] PHP Fatal error: Uncaught Error: Call to undefined method Error::getStatusCode() in /home/smknmop2/erapor.smkn1mopuya.sch.id/app/Exceptions/Handler.php:55 Stack trace: #0 /home/smknmop2/erapor.smkn1mopuya.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(439): App\Exceptions\Handler->App\Exceptions{closure}() #1 /home/smknmop2/erapor.smkn1mopuya.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(369): Illuminate\Foundation\Exceptions\Handler->renderViaCallbacks() #2 /home/smknmop2/erapor.smkn1mopuya.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): Illuminate\Foundation\Exceptions\Handler->render() #3 /home/smknmop2/erapor.smkn1mopuya.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse() #4 /home/smknmop2/erapor.smkn1mopuya.sch.id/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException() #5 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap{closure}() #6 {main} thrown in /home/smknmop2/erapor.smkn1mopuya.sch.id/app/Exceptions/Handler.php on line 55 ![Screenshot 2024-06-11 020518](https://private-user-images.githubusercontent.com/172308247/338295353-7dfb9963-1b6f-4761-b145-6807742a3101.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTIwMzksIm5iZiI6MTcxODA5MTczOSwicGF0aCI6Ii8xNzIzMDgyNDcvMzM4Mjk1MzUzLTdkZmI5OTYzLTFiNmYtNDc2MS1iMTQ1LTY4MDc3NDJhMzEwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwNzQyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTVlYWVlYzkyMGUwNGUzYmE1NWI2MzBmNmI1MDIxN2ZjNGU5ZjFiZjQ1OWZlM2Q0ODFjZjZlYjc4M2RlODEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B4drdC-gtT4V3V-yFlhduRO2sfSvE0riZf7yDsLYarw) ![Screenshot 2024-06-11 012548](https://private-user-images.githubusercontent.com/172308247/338295393-7d387242-2a58-4d0e-8194-58b98e29d84c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTIwMzksIm5iZiI6MTcxODA5MTczOSwicGF0aCI6Ii8xNzIzMDgyNDcvMzM4Mjk1MzkzLTdkMzg3MjQyLTJhNTgtNGQwZS04MTk0LTU4Yjk4ZTI5ZDg0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwNzQyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTcwNTg4YzY3ZjI3M2VlYjk2ZGYyM2UzZTJhOTBiMDhkMzI2OTJjNmZkNGFkMjYxM2ExZmIxMmE3ZDVmOTgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xtBbAEzuh2MaYiIYYwBSEbRmHzdpHjwozt_F9hsHBiE)
> 
> Apakah hostingnya support database postgresql

Suport Pak

**Comment by masadi** [comment]
jalankan juga di ssh:
```composer update```
dan 
```php artisan erapor:update```

Pastikan 2 command di atas sukses tanpa ada error
